# Generated by Django 5.0.4 on 2024-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_tables',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('standard', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
