# Generated by Django 5.0.4 on 2024-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='Faces/'),
        ),
    ]
